apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: capstone-
build:
  artifacts:
  - image: nginx-angular-jumpstart
    context: .docker
    docker:
      dockerfile: nginx.dev.dockerfile
  - image: node-service-jumpstart
    context: .docker
    docker:
      dockerfile: node.dockerfile
deploy:
  kubectl:
    manifests:
    - codewithdan-network-networkpolicy.yaml
    - docker-env-app-development-env-configmap.yaml
    - docker-env-mongo-development-env-configmap.yaml
    - mongo-deployment.yaml
    - mongo-service.yaml
    - nginx-deployment.yaml
    - nginx-service.yaml
    - node-deployment.yaml
    - node-service.yaml
    - redis-deployment.yaml
    - redis-service.yaml
